AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crossroads-lambda

  Lambda services for Crossroads
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 23
    Runtime: nodejs12.x

Resources:
  CrossroadsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: CrossroadsTokenAuthorizer
        Authorizers:
          CrossroadsTokenAuthorizer:
            FunctionArn: !GetAtt PlayerAuthFunction.Arn

  CrossroadsAuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref CrossroadsApi
            Path: /hello
            Method: get

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/login/
      Handler: login.handler
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref CrossroadsAuthApi
            Path: /login
            Method: post
      Policies:
        - AmazonRDSDataFullAccess
        - arn:aws:iam::597880501761:policy/CrossroadsSecretsManagerRead

  PlayerAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: authorizer.handler
      Policies:
        - arn:aws:iam::597880501761:policy/CrossroadsSecretsManagerRead

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${CrossroadsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CrossroadsAuthApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${CrossroadsAuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
